version: '3.8'

services:
  postgres:
    container_name: bookbazar-postgres
    image: postgres:16
    restart: unless-stopped
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: bookbazar
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
